name: Package phenopackets

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  # Path to directory that contains the cohorts, one cohort per folder.
  NOTEBOOK_DIR: notebooks

jobs:
  generate-phenopackets:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.12'

      - name: Install the phenopacket-store package
        run: |
          python3 -m pip install .

      - name: Package the phenopackets
        run: |
          python3 -m ppktstore package --notebook-dir "${NOTEBOOK_DIR}" --format zip tgz --output all_phenopackets

      - name: Upload the phenopacket archives
        uses: actions/upload-artifact@v4
        with:
          name: phenopacket-store
          path: all_phenopackets.(zip|tgz)
          retention-days: 7
